### ISSUE TITLE
DataGeneratorTool Output File Efficiency

### ISSUE THREAD

**Issue by jhunterh** [jhunterh/Cache-Hierarchy-Simulation-Tool#1]
Need to update the DataGenerator to rollover output files when they reach a certain size.
Need to update the DataGenerator to improve efficiency of writing to output file. Writing to file on every load and store is causing performance issues.

**Comment by CapdinCrando** [comment]
I concur, you may want to store the data in a vector of a struct type, then write to file after the program is finished. With file IO pipe optimization, it should write faster that way.
