### ISSUE TITLE
Investigate a unified executable

### ISSUE THREAD

**Issue by CapdinCrando** [jhunterh/Cache-Hierarchy-Simulation-Tool#14]
This unified executable would call the API in the PIN tool after it completes, eliminating the need for the file, which is becoming increasingly big. It may offer a speed and convenience improvement, or be awfully slow. Testing will tell.

**Comment by jhunterh** [comment]
So one pro I can think of for having separate executables is that the same dataset can be used repeatedly in the simulator. That way you know you have consistency with the dataset across multiple runs of the simulator. Just a thought.

**Comment by CapdinCrando** [comment]
That is true, I will probably just close this ticket, then.
