### ISSUE TITLE
Update config file structure

### ISSUE THREAD

**Issue by jhunterh** [jhunterh/Cache-Hierarchy-Simulation-Tool#45]
After talking with Dr. Milenkovic, we need to get the number of cores from the machine that the trace is produced from. This means that the number of cores will be read from the dataset. To make this work, the config file will define the cache hierarchy for a single core that will be duplicated at runtime across all cores. We also need to update the config file parser to read multiple systems from the config file. 

The new config file structure will be as follows:
Define a list of systems, each system will have a list of caches for the core with the first cache describing L1, second L2, etc...
Each system will also have a list of shared caches with the first being the first shared cache layer, and so on.

**Comment by CapdinCrando** [comment]
- Add address size (eg 32-bit) to hardware info file, use for system
- OR if unable to get address size from program, then remove all address space parameters and set to a constant somewhere
