### ISSUE TITLE
Does it make sense to display AMAT for individual caches?

### ISSUE THREAD

**Issue by jhunterh** [jhunterh/Cache-Hierarchy-Simulation-Tool#64]
There seems to be a bug in the simulator causing access times to not be accurate in basic cache objects. This only really applies to cache misses since the access time for a hit is always the latency of the cache itself. 

This got me thinking about whether or not it even makes sense to display AMAT for all objects in the system. Isn't the only really helpful AMAT the system level AMAT? Does it make sense to display AMAT for all levels of the system or just for the top level system?

**Comment by CapdinCrando** [comment]
I think you may be correct. I did originally only report it for the system, but added it per cache later. Also considering the bug, yes, it may be best to take it out.
